### ISSUE TITLE
Is there a way to change the border and opacity of points?

### ISSUE THREAD

**Issue by sandipde** [cosmo-epfl/chemiscope#135]
Hi,
  Is there a easy way to disable/change the default black border of the points ? Also having an option to set the opacity of the points would be nice. if these are complicated to implement, can you  direct me the right places of the code so that I can make a hard coded changes for my own use ?
Thanks !

**Comment by Luthaf** [comment]
There is way to do this for now, and we are a bit weary of adding too many customization options, since they take space in the UI and take maintenance resources. 

If you want to do the changes on your own instance of chemiscope, the code passing these settings to plotly is here for the main trace
https://github.com/cosmo-epfl/chemiscope/blob/9ec79b6c604f02be30afb467a0d7da734d761ea0/src/map/map.ts#L591-L597

and here for the selected points in 3D mode:
https://github.com/cosmo-epfl/chemiscope/blob/9ec79b6c604f02be30afb467a0d7da734d761ea0/src/map/map.ts#L621-L625

We are exploring opacity customization from properties in #113.

**Comment by sandipde** [comment]
Thanks a lot :-).
