### ISSUE TITLE
`atom` properties are stored as `structure` properties while writing input file

### ISSUE THREAD

**Issue by cyrus80** [cosmo-epfl/chemiscope#185]
`write_input` method produces a JSON file where the `"set"` property in the code below is stored as a `"structure"` property.

```python
properties = {
    "PCA": {
        "target": "atom",
        "values": T
    },
    "set": {
        "target": "atom",
        "values": l
    }
}

write_input("soap_pca.json.gz", frames=frames, properties=properties, cutoff=3.5)
```
where `T` is a numpy array with shape (217506, 10) and `flaot64` datatype, `l` is a numpy array with shape (217506, ) and `int64` datatype, and `frames` contains 6962 structures with a total of 217506 atoms.

**Comment by Luthaf** [comment]
After checking @cyrus80 files, I think I understand what is going on here: the frame also contains a property called `set`, which is used instead of the one provided in `properties`. I'll change the code to make sure user-provided properties take precedence here.

In the mean time, a simple fix would be to change the name of the property from`set` to something like `set_per_atom`.
